export const CHANGE_CATE_LIST = 'songs/CHANGE_CATE_LIST'
export const CHANGE_CURRENT_CATE_SONGS = 'songs/CHANGE_CURRENT_CATE_SONGS'
export const CHANGE_CURRENT_CATE_SONGS_NAME = 'songs/CHANGE_CURRENT_CATE_SONGS_NAME'