export const CHANGE_CATE_LIST = 'ranking/CHANGE_CATE_LIST'
export const CHANGE_CURRENT_CATE = 'ranking/CHANGE_CURRENT_CATE'
export const CHANGE_CURRENT_CATE_INDEX = 'ranking/CHANGE_CURRENT_CATE_INDEX'