export const CHANGE_CATEGORIES = 'djradio/CHANGE_CATEGORIES'
export const CHANGE_CURRENT_CATE_ID = 'djradio/CHANGE_CURRENT_CATE_ID'
export const CHANGE_RECOMMENDS = 'djradio/CHANGE_RECOMMENDS'
export const CHANGE_RANKING_LIST = 'djradio/CHANGE_RANKING_LIST'
